### PR TITLE
fix: create table if not exists

### PR DESCRIPTION
**Pull request by keroro520**

### CODE REVIEW

**Comment by classicalliu** [comment]
Why need to add if not exists condition when create table ?

**Comment by keroro520** [comment]
> Why need to add if not exists condition when create table ?

`kicker stop && kicker start` will re-execute the [`web3 entrypoint.sh`](https://github.com/RetricSu/godwoken-kicker/blob/compatibility-changes/docker/web3/entrypoint.sh), and web3 will fail with "table already exist"

**Comment by classicalliu** [comment]
> > Why need to add if not exists condition when create table ?
> 
> `kicker start && kicker stop && kicker start` will re-execute the [`web3 entrypoint.sh`](https://github.com/RetricSu/godwoken-kicker/blob/compatibility-changes/docker/web3/entrypoint.sh), and web3 will fail with "table already exist"

Which version of kicker can reproduce it ? 

Migration will save status to `knex_migrations`, such as which migrations has already executed.

`yarn knex migration:latest` will only execute migrations which not executed before.

**Comment by keroro520** [comment]
> > > Why need to add if not exists condition when create table ?
> > 
> > 
> > `kicker start && kicker stop && kicker start` will re-execute the [`web3 entrypoint.sh`](https://github.com/RetricSu/godwoken-kicker/blob/compatibility-changes/docker/web3/entrypoint.sh), and web3 will fail with "table already exist"
> 
> Which version of kicker can reproduce it ?
> 
> Migration will save status to `knex_migrations`, such as which migrations has already executed.
> 
> `yarn knex migration:latest` will only execute migrations which not executed before.

Is `knex_migrations` a PG table? I mean, where was it saved?

**Comment by keroro520** [comment]
I have forgotten how to reproduce it.
Let's hold this PR and wait for a failed example.

**Pull request closed without merging**
