### PR TITLE
feat: disallow meta contract tx, add parser tooling

### PR DESCRIPTION
**Pull request by RetricSu**
deps:
- https://github.com/nervosnetwork/godwoken-web3/pull/453

### CODE REVIEW

**Comment by keroro520** [comment]
Why meta transactions should be verified in Web3?

**Comment by RetricSu** [comment]
> Why meta transactions should be verified in Web3?

verify min tx fee requirements to avoid dos

**Comment by keroro520** [comment]
> > Why meta transactions should be verified in Web3?
> 
> verify min tx fee requirements to avoid dos

Can we disallow meta transactions in Web3?

**Comment by RetricSu** [comment]
> > > Why meta transactions should be verified in Web3?
> > 
> > 
> > verify min tx fee requirements to avoid dos
> 
> Can we disallow meta transactions in Web3?

meta create account tx might need to be supported since it is a feature. batch create accounts can be disallowed or controled under tx fee like this pr. needs discussion.

**Review by zeroqn — APPROVED** [review]

**Review by keroro520 — APPROVED** [review]

**Review by Flouse — APPROVED** [review]

**Pull request merged**
